---
version: "2.1"
services:
  webtop:
    image: ghcr.io/linuxserver/webtop:
    container_name: webtop
    privileged: true #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /path/to/data:/config
    ports:
      - 3000:3000
    shm_size: "1gb"
    restart: unless-stopped